### 회원 가입 & 이메일 발송
POST http://localhost:3000/user
content-type: application/json

{
  "email": "ottogi99@gmail.com",
  "password": "sunghwa",
  "username": "sunghwa"
}

### 이메일 인증
POST http://localhost:3000/user/email-verify?signupVerifyToken=test_token

### 로그인
POST http://localhost:3000/user/login
content-type: application/json

{
  "email": "sunghwa@onthesys.com",
  "password": "sunghwa"
}

### 회원정보 조회
GET http://localhost:3000/user/1


### 유저생성 요청
POST http://localhost:3000/user
Content-Type: application/json

{
  "email": "sunghwa7149@gmail.com",
  "password": "sunghwa1@",
  "username": "sunghwa"
}

### 로그인
POST http://localhost:3000/user/login
Content-Type: application/json

{
  "email": "sunghwa7149@gmail.com",
  "password": "sunghwa1@"
}

### 회원 정보 조회
GET http://localhost:3000/user/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJzdW5naHdhIiwiZW1haWwiOiJzdW5naHdhNzE0OUBnbWFpbC5jb20iLCJpYXQiOjE2ODc4NTU3MzYsImV4cCI6MTY4Nzg1NTc5NiwiYXVkIjoib250aGVzeXMuY29tIiwiaXNzIjoib250aGVzeXMuY29tIn0.fno-GjGFp1tI2IA1mvAoFnJ5CJUkDrFY2RgODiGdjs4


### 이메일 형식이 잘못된 경우
POST http://localhost:3000/user
Content-Type: application/json

{
  "email": "@onthesys.com",
  "password": "sunghwa1@",
  "username": "wjdtjdghk"
}

### 패스워드 길이가 짧은 경우
POST http://localhost:3000/user
Content-Type: application/json

{
  "email": "sunghwa@onthesys.com",
  "password": "a1234",
  "username": "wjdtjdghk"
}
