### 회원 가입 & 이메일 발송
POST http://localhost:3000/user
content-type: application/json

{
  "email": "ottogi99@gmail.com",
  "password": "sunghwa",
  "username": "sunghwa"
}

### 이메일 인증
POST http://localhost:3000/user/email-verify?signupVerifyToken=test_token
"email": "sunghwa@onthesys.com",

### 로그인
POST http://localhost:3000/user/login
content-type: application/json

{
  "email": "sunghwa@onthesys.com",
  "password": "sunghwa"
}

### 회원정보 조회
GET http://localhost:3000/user/1


